export interface CatalogEntry {
  id: string;
  bank: string;
  name: string;
  min: number;
  blockPts: number;
  blockMiles: number;
  fee: number;
  note: string;
  source: string;
  asOf: string;
  confidence: "high" | "medium" | "low";
}

// Provenance fields (`source`, `asOf`, `confidence`) must stay in sync with
// src/data.js. Rates verified Jun 2026 against the SQ KrisFlyer partner page
// and cross-referenced SG sources. "low"/"medium" confidence values carry a
// caveat in `note` because they could not be confirmed against a primary T&C.
const SQ_PARTNERS =
  "https://www.singaporeair.com/en_UK/sg/ppsclub-krisflyer/earn-miles/earn-on-the-ground/financial-services-partners/";

export const CATALOG: CatalogEntry[] = [
  {
    id: "krisflyer",
    bank: "Direct",
    name: "KrisFlyer Miles",
    min: 0,
    blockPts: 1,
    blockMiles: 1,
    fee: 0,
    note: "Already in your account",
    source: SQ_PARTNERS,
    asOf: "2026-06-17",
    confidence: "high",
  },
  {
    id: "dbs",
    bank: "DBS",
    name: "DBS Points",
    min: 5000,
    blockPts: 5000,
    blockMiles: 10000,
    fee: 27.25,
    note: "Altitude points never expire",
    source: SQ_PARTNERS,
    asOf: "2026-06-17",
    confidence: "high",
  },
  {
    id: "uob",
    bank: "UOB",
    name: "UNI$",
    min: 5000,
    blockPts: 5000,
    blockMiles: 10000,
    fee: 27,
    note: "UNI$ expire after 2 years · fee raised to S$27 Dec 2025",
    source: SQ_PARTNERS,
    asOf: "2026-06-17",
    confidence: "high",
  },
  {
    id: "ocbc90n",
    bank: "OCBC",
    name: "90°N Miles / Travel$",
    min: 1000,
    blockPts: 1000,
    blockMiles: 1000,
    fee: 25,
    note: "1:1 · S$25 conversion fee (since Feb 2023)",
    source: SQ_PARTNERS,
    asOf: "2026-06-17",
    confidence: "high",
  },
  {
    id: "ocbcd",
    bank: "OCBC",
    name: "OCBC$ (Rewards / Premier VI)",
    min: 25000,
    blockPts: 25000,
    blockMiles: 10000,
    fee: 25,
    note: "For Rewards & Premier VI cards",
    source: SQ_PARTNERS,
    asOf: "2026-06-17",
    confidence: "high",
  },
  {
    id: "citytyp",
    bank: "Citi",
    name: "ThankYou Points",
    min: 25000,
    blockPts: 25000,
    blockMiles: 10000,
    fee: 27.25,
    note: "2.5:1 ratio",
    source: SQ_PARTNERS,
    asOf: "2026-06-17",
    confidence: "high",
  },
  {
    id: "citimiles",
    bank: "Citi",
    name: "Citi Miles (PremierMiles)",
    min: 10000,
    blockPts: 1,
    blockMiles: 1,
    fee: 27.25,
    note: "1:1 · min 10,000 transfer block via Citi app",
    source: SQ_PARTNERS,
    asOf: "2026-06-17",
    confidence: "high",
  },
  {
    id: "hsbc",
    bank: "HSBC",
    name: "Reward Points",
    min: 30000,
    blockPts: 3,
    blockMiles: 1,
    fee: 0,
    note: "3:1 · first transfer is the full 30k block, then top-ups",
    source: SQ_PARTNERS,
    asOf: "2026-06-17",
    confidence: "high",
  },
  {
    id: "sc1",
    bank: "Std Chartered",
    name: "360° Tier 1 (Beyond/Journey/VI)",
    min: 25000,
    blockPts: 25000,
    blockMiles: 10000,
    fee: 27.25,
    note: "Preferential 2.5:1 tier",
    source: SQ_PARTNERS,
    asOf: "2026-06-17",
    confidence: "high",
  },
  {
    id: "sc2",
    bank: "Std Chartered",
    name: "360° Tier 2 (Smart/Rewards+)",
    min: 34500,
    blockPts: 34500,
    blockMiles: 10000,
    fee: 27.25,
    note: "3.45:1 tier",
    source: SQ_PARTNERS,
    asOf: "2026-06-17",
    confidence: "high",
  },
  {
    id: "amex",
    bank: "Amex",
    name: "Membership Rewards",
    min: 1000,
    blockPts: 11,
    blockMiles: 5,
    fee: 0,
    note: "2.2:1 generic cards (Platinum Charge 2:1) · devalued Feb 2026",
    source: SQ_PARTNERS,
    asOf: "2026-06-17",
    confidence: "high",
  },
  {
    id: "maybank",
    bank: "Maybank",
    name: "TREATS Points",
    min: 25000,
    blockPts: 25000,
    blockMiles: 10000,
    fee: 27.25,
    note: "2.5:1 via TREATS SG app · Horizon Visa / World Mastercard",
    source: SQ_PARTNERS,
    asOf: "2026-06-17",
    confidence: "high",
  },
  {
    id: "boc",
    bank: "BOC",
    name: "BOC Elite Miles (BOC Points)",
    min: 50000,
    blockPts: 50000,
    blockMiles: 10000,
    fee: 30.56,
    note: "5:1 · Elite Miles card (other BOC reward cards 6:1) · fee incl GST",
    source:
      "https://milelion.com/2025/06/08/boc-elite-miles-card-enhances-earn-rates-removes-asia-miles-excludes-cardup-and-ipaymy/",
    asOf: "2026-06-17",
    confidence: "high",
  },
  {
    id: "cimb",
    bank: "CIMB",
    name: "CIMB Bonus Points",
    min: 75000,
    blockPts: 75000,
    blockMiles: 5000,
    fee: 0,
    note: "15:1 · conversion fee assumed S$0 (unverified)",
    source: "https://www.refinedpoints.com/post/live-cimb-introduces-krisflyer-miles-conversion",
    asOf: "2026-06-17",
    confidence: "medium",
  },
  {
    id: "diners",
    bank: "Diners Club",
    name: "DCS Club Rewards",
    min: 4500,
    blockPts: 4500,
    blockMiles: 1000,
    fee: 0,
    note: "4.5:1 · min/fee unconfirmed",
    source: SQ_PARTNERS,
    asOf: "2026-06-17",
    confidence: "low",
  },
  {
    id: "ntuclink",
    bank: "NTUC Link",
    name: "LinkPoints (via Link Rewards)",
    min: 100,
    blockPts: 2,
    blockMiles: 1,
    fee: 0,
    note: "2:1 · via NTUC Link (Trust Bank path) · min 100 LinkPoints",
    source: "https://www.link.sg/exchange/6-krisflyer",
    asOf: "2026-06-17",
    confidence: "medium",
  },
];

export const BANK_COLORS: Record<string, string> = {
  Direct: "#C4974A",
  DBS: "#E31837",
  UOB: "#003087",
  OCBC: "#EE2E24",
  Citi: "#003B9F",
  HSBC: "#DB0011",
  "Std Chartered": "#0B9444",
  Amex: "#016FD0",
  Maybank: "#FFCC00",
  BOC: "#C8102E",
  CIMB: "#A6093D",
  "Diners Club": "#0079BE",
  "NTUC Link": "#0DB14B",
};

export const BANK_TO_ID: Record<string, string> = {
  KrisFlyer: "krisflyer",
  DBS: "dbs",
  UOB: "uob",
  "OCBC 90N": "ocbc90n",
  "OCBC Rewards": "ocbcd",
  "Citi ThankYou": "citytyp",
  "Citi Miles": "citimiles",
  HSBC: "hsbc",
  "SC Tier1": "sc1",
  "SC Tier2": "sc2",
  Amex: "amex",
  Maybank: "maybank",
  BOC: "boc",
  CIMB: "cimb",
  "Diners Club": "diners",
  "NTUC Link": "ntuclink",
};
