export const T = {
  bg: "#0E1117",
  surface: "#161B27",
  surfaceHi: "#1C2333",
  hover: "#212840",
  border: "#2A3347",
  borderHi: "#3A4560",
  gold: "#C4974A",
  goldSoft: "#E8C882",
  goldDim: "rgba(196,151,74,0.12)",
  ink: "#EDE8DF",
  mist: "#8B96A8",
  faint: "#4A5568",
  good: "#6BAF89",
  goodDim: "rgba(107,175,137,0.12)",
  warn: "#C97B5A",
  warnDim: "rgba(201,123,90,0.12)",
  display: "'Cormorant Garamond', Georgia, serif",
  body: "'Inter', system-ui, sans-serif",
  mono: "'JetBrains Mono', 'Fira Mono', monospace",
};

// Shared page layout styles used by all tabs
export const P = {
  page: { padding: "0 20px 20px" },
  pageHeader: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    padding: "32px 0 24px",
    borderBottom: `1px solid ${T.border}`,
    marginBottom: 28,
  },
  pageHeaderSub: {
    fontFamily: T.mono,
    fontSize: 10,
    letterSpacing: "0.18em",
    color: T.faint,
    textTransform: "uppercase",
    marginBottom: 4,
  },
  pageHeaderTitle: {
    fontFamily: T.display,
    fontSize: 28,
    fontWeight: 600,
    color: T.ink,
    lineHeight: 1,
  },
  kfBadge: {
    fontFamily: T.mono,
    fontSize: 11,
    color: T.mist,
    background: T.surface,
    border: `1px solid ${T.border}`,
    borderRadius: 8,
    padding: "6px 10px",
  },
  hero: {
    textAlign: "center",
    padding: "32px 0 28px",
    marginBottom: 28,
    borderBottom: `1px solid ${T.border}`,
  },
  heroLabel: {
    fontFamily: T.mono,
    fontSize: 10,
    letterSpacing: "0.24em",
    color: T.faint,
    textTransform: "uppercase",
    marginBottom: 14,
  },
  heroNumber: {
    fontFamily: T.display,
    fontSize: "clamp(60px,16vw,88px)",
    fontWeight: 600,
    lineHeight: 1,
    color: T.goldSoft,
    textShadow: `0 0 40px rgba(196,151,74,0.2)`,
  },
  heroUnit: {
    fontFamily: T.mono,
    fontSize: 10,
    letterSpacing: "0.3em",
    color: T.faint,
    textTransform: "uppercase",
    marginTop: 10,
  },
  heroRule: {
    height: "1px",
    background: `linear-gradient(90deg,transparent,${T.gold},transparent)`,
    margin: "18px auto",
    width: "50%",
    maxWidth: 180,
  },
  heroPills: {
    display: "flex",
    gap: 8,
    justifyContent: "center",
    flexWrap: "wrap",
  },
  section: { marginBottom: 30 },
  sectionHead: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
};
